/* Vectoria Quest — bright Three.js courtyard gameplay */
(()=>{
'use strict';
const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
let T=null,active=null,booting=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist2=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function floorId(){try{if(typeof state!=='undefined'&&state.currentFloor)return +state.currentFloor}catch(e){}const n=(document.querySelector('#floorName')?.textContent||'').match(/(\d+)/);return n?+n[1]:1}
function questForFloor(id){try{return typeof quests!=='undefined'?quests.find(q=>q.id===id):null}catch(e){return null}}
function showToast(text){if(!active)return;const el=active.toast;el.textContent=text;el.classList.add('show');clearTimeout(active.toastTimer);active.toastTimer=setTimeout(()=>el.classList.remove('show'),1500)}
function updateMission(){if(!active)return;const m=document.querySelector('#missionText');if(m)m.textContent=active.collected<3?`เก็บคริสตัล ${active.collected} / 3`:'ประตูบอสเปิดแล้ว!'}
function bossEnter(){const q=questForFloor(active?.floor||1);cleanup();try{if(typeof renderQuest==='function'&&q){state.currentQuest=q.id;renderQuest(q.id);return}if(typeof openQuest==='function'&&q){openQuest(q.id);return}}catch(e){console.warn(e)}document.querySelector('#sampleQuestBtn')?.click()}
function mat(color,em=0,rough=.72,metal=.08){return new T.MeshStandardMaterial({color,emissive:em,roughness:rough,metalness:metal})}
function mesh(geo,material,x,y,z,scene){const m=new T.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
function box(w,h,d,color,x,y,z,scene,em=0){return mesh(new T.BoxGeometry(w,h,d),mat(color,em),x,y,z,scene)}
function pillar(x,z,scene){box(1.25,5.2,1.25,0x68756f,x,2.6,z,scene);box(1.58,.4,1.58,0x87958c,x,5.02,z,scene);const moss=box(1.18,.18,1.18,0x587447,x,4.74,z,scene);moss.material.roughness=1}
function bush(x,z,scene){const g=new T.Group();for(let i=0;i<4;i++){const b=new T.Mesh(new T.IcosahedronGeometry(.42+(i%2)*.12,0),mat(i%2?0x567b38:0x6e9147));b.position.set((i-1.5)*.27,.35+Math.random()*.18,(i%2)*.25);g.add(b)}g.position.set(x,0,z);scene.add(g)}
function tree(x,z,scene){const g=new T.Group();const trunk=new T.Mesh(new T.CylinderGeometry(.22,.3,2.3,8),mat(0x6d4b2c));trunk.position.y=1.15;g.add(trunk);for(let i=0;i<3;i++){const c=new T.Mesh(new T.IcosahedronGeometry(1.05-i*.15,1),mat(i===1?0x4f7e36:0x5f9141));c.position.set((i-1)*.34,2.55+i*.2,(i%2-.5)*.3);g.add(c)}g.position.set(x,0,z);scene.add(g)}
function labelSprite(text,color='#ffffff',bg='rgba(15,20,28,.82)',w=320,h=74){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=bg;x.roundRect(4,4,w-8,h-8,14);x.fill();x.fillStyle=color;x.font='700 28px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,w/2,h/2);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthTest:false}));s.scale.set(3.8,.88,1);return s}
function crystal(x,z,color,scene,label){const g=new T.Group();const gem=new T.Mesh(new T.OctahedronGeometry(.72,0),mat(color,color,.2,.32));gem.position.y=1.28;gem.castShadow=true;g.add(gem);const pedestal=new T.Mesh(new T.CylinderGeometry(.72,.9,.55,8),mat(0x6d746d));pedestal.position.y=.28;g.add(pedestal);const ring=new T.Mesh(new T.TorusGeometry(.86,.055,8,36),new T.MeshBasicMaterial({color,transparent:true,opacity:.72}));ring.rotation.x=Math.PI/2;ring.position.y=.72;g.add(ring);const light=new T.PointLight(color,2.3,6,2);light.position.y=1.7;g.add(light);const tag=labelSprite(label,'#f7fbff','rgba(18,27,35,.78)',300,62);tag.position.set(0,2.65,0);tag.scale.set(3.2,.66,1);g.add(tag);g.position.set(x,0,z);g.userData={kind:'crystal',taken:false,gem,ring,baseY:1.28};scene.add(g);return g}
function npc(x,z,scene){const g=new T.Group();const robe=new T.Mesh(new T.ConeGeometry(.58,1.55,7),mat(0xe3e8df));robe.position.y=.78;const trim=new T.Mesh(new T.ConeGeometry(.48,1.22,7),mat(0x32485f));trim.position.y=.75;trim.scale.set(.92,1,.92);const head=new T.Mesh(new T.SphereGeometry(.34,18,12),mat(0xeac5a5));head.position.y=1.78;const hair=new T.Mesh(new T.SphereGeometry(.38,16,10,0,Math.PI*2,0,Math.PI*.55),mat(0x737b83));hair.position.y=1.9;const halo=new T.Mesh(new T.TorusGeometry(.55,.04,8,28),new T.MeshBasicMaterial({color:0xffd34f}));halo.position.y=2.45;halo.rotation.x=Math.PI/2;g.add(robe,trim,head,hair,halo);const mark=labelSprite('! รับโจทย์','#ffd34f','rgba(34,27,8,.8)',230,62);mark.position.set(0,3.12,0);mark.scale.set(2.4,.64,1);g.add(mark);g.position.set(x,0,z);g.userData={kind:'npc',halo};scene.add(g);return g}
function door(x,z,scene){const g=new T.Group();box(1.1,5.2,1.2,0x59635f,-2.4,2.6,0,g);box(1.1,5.2,1.2,0x59635f,2.4,2.6,0,g);box(5.9,.9,1.2,0x6d7871,0,5.0,0,g);const portal=new T.Mesh(new T.PlaneGeometry(3.75,4.1),new T.MeshBasicMaterial({color:0x9a2138,transparent:true,opacity:.6,side:T.DoubleSide}));portal.position.y=2.35;g.add(portal);const rune=new T.Mesh(new T.TorusGeometry(1.72,.1,8,42),new T.MeshBasicMaterial({color:0xff465d,transparent:true,opacity:.95}));rune.position.y=2.35;rune.rotation.y=Math.PI/2;g.add(rune);const red=new T.PointLight(0xff4058,3,8,2);red.position.set(0,2.6,.8);g.add(red);const tag=labelSprite('ห้องบอส','#ffdfdf','rgba(80,7,17,.82)',250,66);tag.position.set(0,6.05,0);g.add(tag);g.position.set(x,0,z);g.userData={kind:'door',portal,rune,open:false,red};scene.add(g);return g}
function player(scene){const g=new T.Group();const legs=new T.Mesh(new T.CylinderGeometry(.42,.5,.95,10),mat(0x24394b));legs.position.y=.55;const body=new T.Mesh(new T.CapsuleGeometry(.45,1.0,6,12),mat(0x2d5f89));body.position.y=1.48;const head=new T.Mesh(new T.SphereGeometry(.37,18,12),mat(0xe9ba91));head.position.y=2.42;const hair=new T.Mesh(new T.ConeGeometry(.43,.52,8),mat(0x49352b));hair.position.y=2.77;const cape=new T.Mesh(new T.BoxGeometry(.74,1.45,.08),mat(0x314f91));cape.position.set(0,1.45,.47);cape.rotation.x=-.1;const sword=new T.Mesh(new T.BoxGeometry(.09,1.35,.09),mat(0xe9f4f6,0x30474a,.2,.8));sword.position.set(.62,1.38,0);sword.rotation.z=-.35;g.add(legs,body,head,hair,cape,sword);g.position.set(0,0,11);scene.add(g);return g}
function monster(x,z,scene,i){const g=new T.Group();const body=new T.Mesh(new T.SphereGeometry(.62,16,12),mat(0x5a2d78,0x1c082d,.5,.05));body.scale.set(1,.85,1.15);body.position.y=.75;const head=new T.Mesh(new T.SphereGeometry(.46,14,10),mat(0x6f398e,0x220a31));head.position.set(0,1.3,-.15);const eyeMat=new T.MeshBasicMaterial({color:0xfff06b});[-.16,.16].forEach(ex=>{const e=new T.Mesh(new T.SphereGeometry(.055,8,6),eyeMat);e.position.set(ex,1.38,-.57);g.add(e)});const hornMat=mat(0xddd3be);[-1,1].forEach(s=>{const h=new T.Mesh(new T.ConeGeometry(.09,.42,7),hornMat);h.position.set(.27*s,1.72,-.08);h.rotation.z=-.45*s;g.add(h)});const wingMat=mat(0x3f1f5e,0x13061e);[-1,1].forEach(s=>{const w=new T.Mesh(new T.ConeGeometry(.55,1.25,3),wingMat);w.position.set(.72*s,1.05,.08);w.rotation.z=s*.78;w.rotation.y=Math.PI/2;g.add(w)});g.add(body,head);const tag=labelSprite(`เวกเตอร์อสูร Lv.${i+1}`,'#ffffff','rgba(59,7,19,.85)',330,64);tag.position.set(0,2.55,0);tag.scale.set(3.3,.65,1);g.add(tag);const barBack=new T.Sprite(new T.SpriteMaterial({color:0x3b1016,depthTest:false}));barBack.position.set(0,2.12,0);barBack.scale.set(2.5,.16,1);const bar=new T.Sprite(new T.SpriteMaterial({color:0xe83f4e,depthTest:false}));bar.position.set(0,2.12,.01);bar.scale.set(2.32,.11,1);g.add(barBack,bar);g.position.set(x,0,z);g.userData={kind:'monster',origin:new T.Vector3(x,0,z),phase:i*1.7,bar,lastHit:0};scene.add(g);return g}
function buildWorld(scene){
 scene.background=new T.Color(0x8cc9ef);scene.fog=new T.Fog(0xb6d7e7,32,78);
 const hemi=new T.HemisphereLight(0xe8f6ff,0x6d7559,2.25);scene.add(hemi);const sun=new T.DirectionalLight(0xfff1c9,3.15);sun.position.set(-10,20,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;scene.add(sun);
 const floor=new T.Mesh(new T.PlaneGeometry(34,48),mat(0xb4aa91));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 for(let x=-16;x<16;x+=2){for(let z=-23;z<23;z+=2){const tile=box(1.9,.08,1.9,((x+z)/2)%2?0xb7ad96:0xc4baa2,x,.04,z,scene);tile.material.roughness=.95}}
 const grid=new T.GridHelper(34,17,0x9a907a,0xc4baa2);grid.position.y=.1;grid.material.opacity=.22;grid.material.transparent=true;scene.add(grid);
 box(35,3,1.2,0x6c746d,0,1.5,-24,scene);box(35,2.1,1.2,0x727b74,0,1.05,24,scene);box(1.2,2.4,48,0x707870,-17,1.2,0,scene);box(1.2,2.4,48,0x707870,17,1.2,0,scene);
 [-13,-7,7,13].forEach(x=>[-18,-7,5,17].forEach(z=>pillar(x,z,scene)));
 [[-15,19],[15,19],[-15,-20],[15,-20],[-12,14],[12,14]].forEach(([x,z])=>tree(x,z,scene));
 [[-14,8],[-12,10],[13,9],[14,3],[-13,-11],[12,-14],[-9,-20],[9,-20]].forEach(([x,z])=>bush(x,z,scene));
 const torches=[[-15,-13],[15,-13],[-15,12],[15,12],[-3,-20],[3,-20]];torches.forEach(([x,z])=>{const pole=box(.16,2.0,.16,0x3c2f25,x,1,z,scene);const flame=new T.Mesh(new T.ConeGeometry(.18,.55,10),new T.MeshBasicMaterial({color:0xff9c31}));flame.position.set(x,2.25,z);scene.add(flame);const l=new T.PointLight(0xff9b42,2.7,7,2);l.position.set(x,2.35,z);scene.add(l)});
}
function buildUI(frame){const stage=document.createElement('div');stage.className='three-stage';stage.innerHTML='<div class="three-crosshair"></div><div class="three-badge"><b>THREE.JS</b> · VECTOR COURTYARD</div><div class="three-prompt"></div><div class="three-toast"></div><div class="three-dialog"><span class="three-dialog-face">🧙</span><div><b>อาจารย์เวกเตอร์</b><p>เก็บคริสตัลเวกเตอร์ทั้ง 3 เม็ด ระวังเวกเตอร์อสูร แล้วไปยังประตูห้องบอส</p></div><button type="button">เข้าใจแล้ว</button></div><div class="three-mobile-stick"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><button class="three-action" type="button">⚔<small>ใช้</small></button>';frame.prepend(stage);return{stage,prompt:stage.querySelector('.three-prompt'),toast:stage.querySelector('.three-toast'),dialog:stage.querySelector('.three-dialog'),action:stage.querySelector('.three-action')}}
async function boot(){if(active||booting)return;const frame=document.querySelector('.game-frame'),source=document.querySelector('#gameCanvas');if(!frame||!source)return;booting=true;try{T=await import(THREE_URL);if(!document.body.contains(frame))return;frame.classList.add('three-active');source.classList.add('three-hidden-source');const ui=buildUI(frame);const scene=new T.Scene(),camera=new T.PerspectiveCamera(58,16/9,.1,140),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.16;ui.stage.prepend(renderer.domElement);buildWorld(scene);const p=player(scene),n=npc(-9,9,scene),d=door(0,-21.8,scene);const crystals=[crystal(-10,-2,0xa657ff,scene,'คริสตัลเวกเตอร์ 1'),crystal(0,-9,0x34e889,scene,'คริสตัลเวกเตอร์ 2'),crystal(10,-4,0x45aaff,scene,'คริสตัลเวกเตอร์ 3')];const monsters=[monster(5,5,scene,0),monster(-4,-5,scene,1),monster(7,-12,scene,2),monster(-8,-14,scene,3)];active={frame,source,ui,...ui,scene,camera,renderer,player:p,npc:n,door:d,crystals,monsters,keys:{},floor:floorId(),collected:0,last:performance.now(),near:null,raf:0,toastTimer:0,lastDamage:0};resize();updateMission();bind();ui.dialog.classList.add('show');loop(performance.now())}catch(err){console.error('Three.js boot failed',err);cleanup()}finally{booting=false}}
function bind(){if(!active)return;active.keydown=e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' '].includes(k))e.preventDefault();active.keys[k]=true;if(k==='e'||k===' ')interact()};active.keyup=e=>active.keys[e.key.toLowerCase()]=false;active.resize=resize;window.addEventListener('keydown',active.keydown,{passive:false});window.addEventListener('keyup',active.keyup);window.addEventListener('resize',active.resize);active.dialog.querySelector('button').onclick=()=>active.dialog.classList.remove('show');active.action.onclick=interact;active.ui.stage.querySelectorAll('[data-dir]').forEach(b=>{const map={up:'w',down:'s',left:'a',right:'d'},k=map[b.dataset.dir];const on=e=>{e.preventDefault();active.keys[k]=true},off=e=>{e.preventDefault();active.keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)})}
function resize(){if(!active)return;const r=active.frame.getBoundingClientRect(),w=Math.max(320,r.width),h=Math.max(240,r.height);active.renderer.setSize(w,h,false);active.camera.aspect=w/h;active.camera.updateProjectionMatrix()}
function interact(){if(!active)return;if(active.near==='npc'){active.dialog.classList.add('show');return}if(active.near==='door'){if(active.collected<3){showToast(`ต้องเก็บคริสตัลอีก ${3-active.collected} เม็ด`);return}bossEnter();return}if(active.near==='monster'){showToast('⚔ ฟันเวกเตอร์อสูร!');const m=active.nearMonster;if(m){m.userData.bar.scale.x=Math.max(.25,m.userData.bar.scale.x-.75);m.userData.lastHit=performance.now();m.position.x+=Math.sign(m.position.x-active.player.position.x)*.65;m.position.z+=Math.sign(m.position.z-active.player.position.z)*.65}}}
function loop(now){if(!active)return;const dt=Math.min(.04,(now-active.last)/1000||.016);active.last=now;const a=active,p=a.player,k=a.keys;let dx=0,dz=0;if(k.w||k.arrowup)dz-=1;if(k.s||k.arrowdown)dz+=1;if(k.a||k.arrowleft)dx-=1;if(k.d||k.arrowright)dx+=1;if(dx||dz){const len=Math.hypot(dx,dz);dx/=len;dz/=len;const speed=6.3;p.position.x=clamp(p.position.x+dx*speed*dt,-15.2,15.2);p.position.z=clamp(p.position.z+dz*speed*dt,-22.0,22.0);p.rotation.y=Math.atan2(dx,dz);p.position.y=Math.abs(Math.sin(now*.012))*.035}
 a.crystals.forEach((c,i)=>{if(c.userData.taken)return;c.rotation.y+=dt*1.55;c.userData.gem.position.y=c.userData.baseY+Math.sin(now*.002+i)*.14;c.userData.ring.rotation.z+=dt*.8;if(dist2(p.position,c.position)<1.35){c.userData.taken=true;c.visible=false;a.collected++;updateMission();showToast(`◆ ได้คริสตัล ${a.collected} / 3`);if(a.collected===3){a.door.userData.open=true;a.door.userData.portal.material.color.setHex(0x27d9b2);a.door.userData.rune.material.color.setHex(0x55ffe0);a.door.userData.red.color.setHex(0x49ffe2);showToast('ประตูบอสเปิดแล้ว!')}}});
 let nearestMonster=null,nearestDist=99;a.monsters.forEach((m,i)=>{const ud=m.userData,origin=ud.origin;const r=2.4+i*.35;m.position.x=origin.x+Math.sin(now*.00055+ud.phase)*r;m.position.z=origin.z+Math.cos(now*.00048+ud.phase)*r*.55;m.rotation.y=Math.sin(now*.001+ud.phase)*.4;const dm=dist2(p.position,m.position);if(dm<nearestDist){nearestDist=dm;nearestMonster=m}if(dm<1.25&&now-a.lastDamage>1300){a.lastDamage=now;showToast('💥 โดนเวกเตอร์อสูรโจมตี!')}});
 a.npc.userData.halo.rotation.z+=dt*.65;a.door.userData.rune.rotation.z+=dt*.35;a.door.userData.portal.material.opacity=a.door.userData.open?.7:.54;const dn=dist2(p.position,a.npc.position),dd=dist2(p.position,a.door.position);a.nearMonster=nearestMonster;a.near=dn<2.4?'npc':dd<3.2?'door':nearestDist<2.2?'monster':null;if(a.near==='npc'){a.prompt.innerHTML='<kbd>E</kbd> คุยกับอาจารย์เวกเตอร์';a.prompt.classList.add('show')}else if(a.near==='door'){a.prompt.innerHTML=a.collected===3?'<kbd>E</kbd> เข้าห้องบอส':'ประตูผนึก · เก็บคริสตัลให้ครบ 3 เม็ด';a.prompt.classList.add('show')}else if(a.near==='monster'){a.prompt.innerHTML='<kbd>E</kbd> โจมตีเวกเตอร์อสูร';a.prompt.classList.add('show')}else a.prompt.classList.remove('show');
 const target=new T.Vector3(p.position.x,p.position.y+1.35,p.position.z-1.1),desired=new T.Vector3(p.position.x,p.position.y+6.4,p.position.z+10.2);a.camera.position.lerp(desired,1-Math.pow(.002,dt));a.camera.lookAt(target);a.renderer.render(a.scene,a.camera);a.raf=requestAnimationFrame(loop)}
function cleanup(){if(!active)return;cancelAnimationFrame(active.raf);window.removeEventListener('keydown',active.keydown);window.removeEventListener('keyup',active.keyup);window.removeEventListener('resize',active.resize);active.renderer?.dispose();active.stage?.remove();active.source?.classList.remove('three-hidden-source');active.frame?.classList.remove('three-active');active=null}
const obs=new MutationObserver(()=>{const canvas=document.querySelector('#gameCanvas');if(canvas&&!active&&!booting)setTimeout(boot,0);else if(!canvas&&active)cleanup()});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('pagehide',cleanup);if(document.querySelector('#gameCanvas'))boot();
})();
